auth:
    resource: "@AuthBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    path: /login
    defaults:  { _controller: AuthBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout
