security:
    encoders:
        Symfony\Component\Security\Core\USer\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: [ROLE_AUTEUR, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    user: { password: password, roles: ['ROLE_USER']}
                    admin: { password: admin, roles: ['ROLE_ADMIN']}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: in_memory
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: /blog



    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
