# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

  #le nom du service
    blog.validator.antiflood:
        class: AppBundle\Validator\AntiFloodValidator
        arguments: [@request, @doctrine.orm.entity_manager]
        scope: request
        # comme on injecte la requête, on doit préciser le Scope.

        tags :
            - { name: validator.constraint_validator, alias: blog_antiflood }
              # c'est avevc l'alias qu'on retrouvera le service.


    app.excel_service:
        class: AppBundle\Services\ExcelService
        arguments: [ "@doctrine.orm.entity_manager",@service_container ]